# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classification', models.CharField(choices=[('F5 BIG-IP', 'F5 BIG-IP')], default='F5 BIG-IP', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='system.DeviceGroup'),
        ),
    ]
