# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20160318_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 29, 19, 43, 37, 391463, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 29, 19, 43, 40, 832079, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 29, 19, 43, 46, 56411, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
