language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.9.4
  - DJANGO_VERSION=1.9.5
# command to install dependencies
install:
  - pip install --user -q Django==$DJANGO_VERSION
#  - python setup.py -q install
  - pip install --user -r requirements.txt

before_script:
  - python manage.py migrate

# command to run tests
script:
  - python manage.py test
