# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.GenericIPAddressField()),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('lb_method', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PoolMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('state', models.CharField(max_length=64)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltm.Node')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltm.Pool')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('vs_type', models.IntegerField(choices=[(0, b'Standard'), (1, b'Forwarding (IP)'), (2, b'Forwarding (Layer 2)'), (3, b'Reject'), (4, b'Performance (Layer 4)'), (5, b'Performance (HTTP)'), (6, b'Stateless')], default=0)),
                ('destination', models.GenericIPAddressField()),
                ('destination_subnet', models.GenericIPAddressField()),
                ('service_port', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('protocol', models.IntegerField(choices=[(0, b'wildcard'), (1, b'IPv6 header'), (2, b'IPv6 routing header'), (3, b'IPv6 no next header'), (4, b'IPv6 fragmentation header'), (5, b'IPv6 destination options'), (6, b'TCP'), (7, b'UDP'), (8, b'ICMP'), (9, b'ICMPv6'), (10, b'OSPF'), (11, b'SCTP')], default=6)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ltm.Pool')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualServerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pool',
            name='members',
            field=models.ManyToManyField(through='ltm.PoolMember', to='ltm.Node'),
        ),
    ]
