# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltm', '0003_auto_20160317_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
