# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltm', '0004_pool_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='state',
            field=models.CharField(default='status_circle_green', max_length=200),
            preserve_default=False,
        ),
    ]
