# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ltm', '0005_auto_20160318_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 29, 19, 42, 49, 438276, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 29, 19, 42, 54, 6622, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 29, 19, 42, 58, 280193, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 29, 19, 43, 3, 19914, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 29, 19, 43, 6, 810493, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 29, 19, 43, 10, 968677, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poolmember',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 29, 19, 43, 14, 560888, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poolmember',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 29, 19, 43, 19, 670708, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poolmember',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 29, 19, 43, 23, 628935, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 29, 19, 43, 26, 970968, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 29, 19, 43, 30, 572148, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 29, 19, 43, 34, 23609, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
