# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltm', '0006_auto_20160329_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='path',
            field=models.CharField(default='/Common', max_length=255),
        ),
        migrations.AlterField(
            model_name='pool',
            name='path',
            field=models.CharField(default='/Common', max_length=255),
        ),
        migrations.AlterField(
            model_name='virtualserver',
            name='path',
            field=models.CharField(default='/Common', max_length=255),
        ),
    ]
