# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20160329_1443'),
        ('ltm', '0007_auto_20160401_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='device_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.DeviceGroup'),
        ),
        migrations.AddField(
            model_name='pool',
            name='device_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.DeviceGroup'),
        ),
    ]
