# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltm', '0009_auto_20160401_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='status_availability',
            field=models.CharField(default='temp', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='status_description',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='status_enabled',
            field=models.CharField(default='temp', max_length=64),
            preserve_default=False,
        ),
    ]
