# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltm', '0011_auto_20160405_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualserver',
            name='vs_type',
            field=models.CharField(max_length=64),
        ),
    ]
